//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace licoreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licores
    {
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public string TipoDeLicor { get; set; }
        public Nullable<int> Precio { get; set; }
        public string Imagen { get; set; }
    }
}
